### ISSUE TITLE
Documentation is missing important details

### ISSUE THREAD

**Issue by slessard** [ragingwind/grunt-chrome-manifest#19]
After spending a lot of time trying to figure out why background.js wasn't being created I finally figured out that chromeManifest assumes certain additional tasks will be executed after the chromeManifest task itself has be executed.  This dependency should be noted in the documentation.

`grunt chromeManifest:dist` will not produce background.js
`grunt concat cssmin uglify chromeManifest:dist` will not produce background.js
`grunt chromeManifest:dist concat cssmin uglify` is the proper recipe for producing background.js

Please consider updating the documentation to state that the chromeManifest task must be run *before* the concat, cssmin and uglify tasks.

**Comment by ragingwind** [comment]
I close the issue, PR always welcome
