### ISSUE TITLE
exclude not working

### ISSUE THREAD

**Issue by brightdroid** [ragingwind/grunt-chrome-manifest#22]
The exclude option doesn't work, so every background file will be used in concat!

Also one should be able to use a list of excludes.

**Comment by ragingwind** [comment]
It's not complicated work see https://github.com/ragingwind/grunt-chrome-manifest/blob/master/tasks/chrome-manifest.js#L54 Did you run the grunt task before do `concat` task?

**Comment by ragingwind** [comment]
I close the issue, if you still have a problem? let me know with your gruntfile
