### ISSUE TITLE
removeFields doesnt work

### ISSUE THREAD

**Issue by ukdvivek** [ragingwind/grunt-chrome-manifest#23]
I am trying to use removeFields to remove 'key' field from manifest using removeFields property.

```javascript
options: {
                    buildnumber: true,
                    background: {
                        target: 'scripts/background.js',
                        exclude: [
                            'scripts/chromereload.js'
                        ]
                    },
                    removeFields: ['key']
                }
```

But the field is still present in build zip file.

**Comment by ragingwind** [comment]
I did face the problem with 'key' property. [I added 'key' property to test](https://github.com/ragingwind/grunt-chrome-manifest/blob/master/test/test-chrome-manifest.js#L228). Take a look. The task generate new manifest.json to `dist` path also check them. I close the issue If you have still the problem reopen this
