### ISSUE TITLE
Background option seems to require a target for even if all background scripts are excluded

### ISSUE THREAD

**Issue by zachlysobey** [ragingwind/grunt-chrome-manifest#24]
In my manifest, I have only one script (`chromereload.js`):

    "background": {
        "scripts": [
            "chromereload.js"
        ]
    },

attempting to exclude this file in the grunt task yields an error

> Warning: Arguments to path.join must be strings Use --force to continue.

__Gruntfile snippet:__

    background: {
        exclude: [
            'chromereload.js'
        ]
    }

adding `target: 'background.js'` resolves this warning, but now the output contains a reference to a blank `background.js` file in the manifest.

**Comment by ragingwind** [comment]
It seems like task cannot handle empty scripts array I will look into it thanks for reporting

**Comment by zachlysobey** [comment]
Glad I can help, and thanks for the quick reply.
Let me know if you think you won't get a chance to fix within a few days; maybe I can figure it out and submit a pull request.

**Comment by ragingwind** [comment]
PR is always welcome

**Comment by zachlysobey** [comment]
I spent an hour or so tinkering but I'm not so good at this whole github/npm thing yet.

I was able to put together a test which *may* help.

I don't think it fully/correctly reproduces my issue (I don't get a `Arguments to path.join must be strings` message)

Also, I noticed the version in NPM seems to be behind the version in github, which was messing me up a bit.

I may be able to spend a bit more time next week (& maybe not), but please let me know if I'm on the right track with this test.

    it('should have empty background.scripts if all background scripts are excluded', function() {
      var target = _.clone(targets.dist, true);
      delete target.options.background.target;
      var manifest = {};

      // manifest in ./temp/app with no background scripts
      manifest.jsonSrc = grunt.file.readJSON(path.join(__dirname, 'fixtures/manifest.json'));
      manifest.jsonSrc.background.scripts = _.reject(manifest.jsonSrc.background.scripts, function(it, index) {
        return target.options.background.exclude.indexOf(it) === -1;
      });
      grunt.file.write(path.join(target.src, 'manifest.json'), JSON.stringify(manifest, null, 4))
      manifest.app = grunt.file.readJSON(path.join(__dirname, 'temp/app/manifest.json'));

      // run the task
      grunt.config.init();
      grunt.config('chromeManifest', {dist: target});
      grunt.task.run('chromeManifest:dist');
      grunt.task.start();

      manifest.dist = grunt.file.readJSON(path.join(target.dest, 'manifest.json'));

      // the resulting manifest has an empty background scripts array
      assert.equal(manifest.dist.background.scripts.length, 0);
    });

**Comment by ragingwind** [comment]
Do you still have the problem with 0.2.3?

**Comment by zachlysobey** [comment]
I'll check it out now.
I see you've been active today! Thanks for keeping up on this stuff. This
tool is great.

Zach Lysobey
(203) 984-4048

**Comment by zachlysobey** [comment]
I now get 0.2.3 when I npm update!

I still have the same issue with background.js however.

Zach Lysobey
(203) 984-4048

**Comment by ragingwind** [comment]
In this case, exclude isn't meaning anymore. I mean, target option should be given otherwise exclude options will be ignored. I post new version to master branch. Please let me know if you are still having problems. https://github.com/ragingwind/grunt-chrome-manifest/commit/ef7531c7d77f252981a5430cb396093ce3b29214

**Comment by zachlysobey** [comment]
Not sure when I'll get back to this... but I'll try to remember to confirm that it fixes my issue.
Thank you!
