### ISSUE TITLE
option to disable uglification

### ISSUE THREAD

**Issue by kumavis** [ragingwind/grunt-chrome-manifest#27]
I want to configure that manually

**Comment by kumavis** [comment]
fwiw, if you run uglify before chromeManifest, you dont need to worry about the extra uglify jobs this task injects

**Comment by ragingwind** [comment]
This grunt plugin is to ties up and uglify the scripts automatically. see [readme](https://github.com/ragingwind/grunt-chrome-manifest#workflow) If you want to manage the grunt tasks manually. Please use other options
